services:
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/hf_models_cache:/app/hf_models_cache
    environment:
      - HF_HOME=/app/hf_models_cache
      - TRANSFORMERS_CACHE=/app/hf_models_cache
      - HUGGINGFACE_HUB_CACHE=/app/hf_models_cache
      - HF_HUB_CACHE=/app/hf_models_cache
  
  docs:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    command: poetry run mkdocs serve -a 0.0.0.0:8001
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules