services:
  
  backend:
    build: ./backend
    ports:
      - "${LUMIXAI_BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
      - ./backend/hf_models_cache:/app/hf_models_cache
    environment:
      - HF_HOME=/app/hf_models_cache
      - TRANSFORMERS_CACHE=/app/hf_models_cache # deprecated (-> HF_HOME), can be removed in the future
      - HUGGINGFACE_HUB_CACHE=/app/hf_models_cache
      - HF_HUB_CACHE=/app/hf_models_cache
      - HF_TOKEN=${HF_TOKEN:-}
      - LUMIXAI_DEFAULT_DEVICE=${LUMIXAI_DEFAULT_DEVICE:-auto}
  
  docs:
    build: ./backend
    ports:
      - "${LUMIXAI_DOCS_PORT:-8001}:8001"
    volumes:
      - ./backend:/app
    command: poetry run mkdocs serve -a 0.0.0.0:8001
  
  frontend:
    build: ./frontend
    ports:
      - "${LUMIXAI_FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
