services:
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/hf_models_cache:/app/hf_models_cache
    # NVIDIA GPU SUPPORT
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  docs:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    command: poetry run mkdocs serve -a 0.0.0.0:8001 # Override
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true