site_name: LumiXAI Documentation
site_description: Modular & Interactive Explainable AI Framework
site_author: Lorenzo Gatta

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate # Table of Contents
  palette:
    - scheme: slate # Dark Mode
      primary: orange
      accent: orange

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]

nav:
  - Home: index.md
  - API Reference:
    - Core Schemas: api/schema.md
    - Database: api/db.md
    - Base Interfaces: api/abstract.md
    - Wrappers: api/wrappers.md
    - Attributors: api/attributors.md
    - Utilities: api/utils.md
    - FastAPI Endpoints: api/main.md