"""Custom implementation of Diffusion Attentive Attribution Maps (DAAM).

This module contains specialized hooks and processors designed to intercept 
cross-attention matrices inside the UNet of Stable Diffusion models during 
the generation process.
"""

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg
import numpy as np
from typing import Optional, List, Dict, Any
from diffusers.models.attention_processor import Attention

class CustomDAAMHeatmap:
    """Manages and processes per-token spatial heatmaps.
    
    This class wraps the raw PyTorch tensor representing the attention map 
    and provides utility methods to overlay it onto the final generated image.
    """
    def __init__(self, heatmap: torch.Tensor):
        """Initializes the heatmap object.

        Args:
            heatmap (torch.Tensor): A 2D PyTorch tensor containing the spatial attention scores.
        """
        self.heatmap = heatmap

    def plot_overlay(self, image: Any) -> Figure:
        """Overlays the heatmap onto the generated PIL Image.

        Uses a robust 1st-99th percentile normalization instead of standard min-max
        scaling. This prevents isolated extreme attention spikes (outliers) from
        washing out the visual representation of the heatmap.

        Uses the object-oriented Matplotlib API (a standalone ``Figure`` with its own
        ``FigureCanvasAgg``) rather than the global ``pyplot`` state machine, so that
        overlays for different tokens can be rendered concurrently from a thread pool.
        The rendered pixels are identical to the previous ``plt.subplots`` version.

        Args:
            image (PIL.Image.Image): The final image generated by the diffusion model.

        Returns:
            matplotlib.figure.Figure: A Matplotlib figure containing the blended overlay.
        """
        w, h = image.size
        heatmap_np = self.heatmap.cpu().numpy()

        vmin = np.percentile(heatmap_np, 1)
        vmax = np.percentile(heatmap_np, 99)

        heatmap_np = np.clip((heatmap_np - vmin) / (vmax - vmin + 1e-8), 0, 1)

        fig = Figure(figsize=(6, 6))
        FigureCanvasAgg(fig)
        ax = fig.subplots()
        ax.imshow(image)
        ax.imshow(heatmap_np, cmap='jet', alpha=0.6, extent=(0, w, h, 0))
        ax.axis('off')
        return fig

class CaptureAttnProcessor:
    """Custom attention processor used as a hook.

    Replaces the standard attention processor in the UNet. It intercepts
    Query, Key, and Value matrices to compute the cross-attention probabilities
    without altering the actual forward pass computation.

    For efficiency the captured maps are aggregated **incrementally on the GPU**
    into a single fixed 64x64 accumulator: maps outside the useful resolution
    range are skipped before any work, and there is exactly one GPU->CPU
    transfer at the end (in ``trace.compute_heat_maps``) instead of one per
    layer per denoising step. This is numerically equivalent to averaging all
    valid maps, but avoids the hundreds of per-step device syncs that dominated
    generation time.
    """
    TARGET_DIM = 64
    MIN_PIXELS = 256
    MAX_PIXELS = 4096

    def __init__(self):
        # Lazily-created GPU accumulator of shape (TARGET_DIM, TARGET_DIM, num_tokens).
        self.accumulator: Optional[torch.Tensor] = None
        self.count = 0

    def _accumulate(self, attn_probs: torch.Tensor) -> None:
        """Fold one cross-attention map (batch*heads, pixels, tokens) into the accumulator."""
        num_pixels = attn_probs.shape[1]
        if not (self.MIN_PIXELS <= num_pixels <= self.MAX_PIXELS):
            return  # skip resolutions we never use (e.g. the huge 1024^2-latent maps)

        side = int(np.sqrt(num_pixels))
        if side * side != num_pixels:
            return

        num_tokens = attn_probs.shape[-1]
        # Average over batch*heads (identical to the previous m.mean(dim=0)), then
        # reshape to a spatial grid and bicubically upscale to TARGET_DIM on-GPU.
        m_avg = attn_probs.mean(dim=0)                                  # (pixels, tokens)
        m_2d = m_avg.view(side, side, num_tokens).permute(2, 0, 1).unsqueeze(1)  # (tokens, 1, side, side)
        m_resized = F.interpolate(
            m_2d.to(torch.float32), size=(self.TARGET_DIM, self.TARGET_DIM),
            mode="bicubic", align_corners=False,
        ).squeeze(1).permute(1, 2, 0)                                  # (TARGET_DIM, TARGET_DIM, tokens)

        if self.accumulator is None:
            self.accumulator = torch.zeros_like(m_resized)
        self.accumulator += m_resized
        self.count += 1

    def __call__(self, attn: Attention, hidden_states: torch.Tensor, encoder_hidden_states: Optional[torch.Tensor]=None, attention_mask: Optional[torch.Tensor]=None, temb: Optional[torch.Tensor]=None, scale: float=1.0) -> torch.Tensor:
        """Executes the attention mechanism and captures cross-attention probabilities."""
        batch_size, sequence_length, _ = hidden_states.shape
        is_cross = encoder_hidden_states is not None
        context = encoder_hidden_states if is_cross else hidden_states

        heads = attn.heads
        dim_head = attn.to_q.out_features // heads

        query = attn.to_q(hidden_states)
        key = attn.to_k(context)
        value = attn.to_v(context)

        query = query.view(batch_size, -1, heads, dim_head).transpose(1, 2).reshape(batch_size * heads, -1, dim_head)
        key = key.view(batch_size, -1, heads, dim_head).transpose(1, 2).reshape(batch_size * heads, -1, dim_head)
        value = value.view(batch_size, -1, heads, dim_head).transpose(1, 2).reshape(batch_size * heads, -1, dim_head)

        attn_scores = torch.bmm(query, key.transpose(1, 2)) * scale
        attn_probs = attn_scores.softmax(dim=-1)

        if is_cross:
            self._accumulate(attn_probs.detach())

        hidden_states = torch.bmm(attn_probs, value)
        hidden_states = hidden_states.reshape(batch_size, heads, -1, dim_head).transpose(1, 2).reshape(batch_size, -1, heads * dim_head)
        hidden_states = attn.to_out[0](hidden_states)
        hidden_states = attn.to_out[1](hidden_states)
        return hidden_states

class trace:
    """Context manager for tracing UNet cross-attention.
    
    Temporarily injects the `CaptureAttnProcessor` into all cross-attention 
    layers of the UNet. Once the generation block exits, it automatically 
    restores the original processors to prevent memory leaks.
    """
    def __init__(self, pipeline: Any):
        """Initializes the tracer.

        Args:
            pipeline (StableDiffusionPipeline): The loaded Hugging Face Diffusers pipeline.
        """
        self.pipeline = pipeline
        self.original_processors = {}
        self.capture_processor = CaptureAttnProcessor()

    def __enter__(self):
        """Injects custom attention hooks into the UNet."""
        unet = self.pipeline.unet
        for name, module in unet.named_modules():
            if name.endswith("attn2") and hasattr(module, "set_processor"):
                self.original_processors[name] = module.processor
                module.set_processor(self.capture_processor)
        return self

    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any):
        """Restores the original attention processors."""
        unet = self.pipeline.unet
        for name, module in unet.named_modules():
            if name in self.original_processors:
                module.set_processor(self.original_processors[name])

    def compute_heat_maps(self) -> Dict[int, CustomDAAMHeatmap]:
        """Aggregates and upscales the captured attention maps.
        
        Averages the attention across all heads and specific UNet layers (typically 16x16 
        up to 64x64 latent spaces), then uses bicubic interpolation to upscale the 
        resulting matrices to a unified 64x64 grid for interactive visualization.

        Returns:
            Dict[int, CustomDAAMHeatmap]: A dictionary mapping the token index (int) to its corresponding upscaled heatmap object.

        Raises:
            ValueError: If no attention maps were captured during the tracing process.
        """
        proc = self.capture_processor
        if proc.accumulator is None or proc.count == 0:
            raise ValueError("No attention captured.")

        # Single GPU->CPU transfer of the aggregated (already interpolated) maps.
        accumulated_maps = (proc.accumulator / proc.count).cpu()
        num_tokens = accumulated_maps.shape[-1]

        results = {}
        for token_idx in range(num_tokens):
            token_map = accumulated_maps[:, :, token_idx]
            if token_map.max() > 0:
                results[token_idx] = CustomDAAMHeatmap(token_map)

        return results