"""Custom implementation of Diffusion Attentive Attribution Maps (DAAM).

This module contains specialized hooks and processors designed to intercept 
cross-attention matrices inside the UNet of Stable Diffusion models during 
the generation process.
"""

import torch
import matplotlib.pyplot as plt
import numpy as np
from typing import Optional, List, Dict, Any
from diffusers.models.attention_processor import Attention

class CustomDAAMHeatmap:
    """Manages and processes per-token spatial heatmaps.
    
    This class wraps the raw PyTorch tensor representing the attention map 
    and provides utility methods to overlay it onto the final generated image.
    """
    def __init__(self, heatmap: torch.Tensor):
        """Initializes the heatmap object.

        Args:
            heatmap (torch.Tensor): A 2D PyTorch tensor containing the spatial attention scores.
        """
        self.heatmap = heatmap

    def plot_overlay(self, image: Any) -> plt.Figure:
        """Overlays the heatmap onto the generated PIL Image.
        
        Uses a robust 1st-99th percentile normalization instead of standard min-max 
        scaling. This prevents isolated extreme attention spikes (outliers) from 
        washing out the visual representation of the heatmap.

        Args:
            image (PIL.Image.Image): The final image generated by the diffusion model.

        Returns:
            matplotlib.figure.Figure: A Matplotlib figure containing the blended overlay.
        """
        w, h = image.size
        heatmap_np = self.heatmap.cpu().numpy()
        
        vmin = np.percentile(heatmap_np, 1)
        vmax = np.percentile(heatmap_np, 99)
        
        heatmap_np = np.clip((heatmap_np - vmin) / (vmax - vmin + 1e-8), 0, 1)
        
        fig, ax = plt.subplots(figsize=(6, 6))
        ax.imshow(image)
        ax.imshow(heatmap_np, cmap='jet', alpha=0.6, extent=(0, w, h, 0))
        ax.axis('off')
        return fig

class CaptureAttnProcessor:
    """Custom attention processor used as a hook.
    
    Replaces the standard attention processor in the UNet. It intercepts 
    Query, Key, and Value matrices to compute and store the cross-attention 
    probabilities without altering the actual forward pass computation.
    """
    def __init__(self):
        self.attention_probs = []

    def __call__(self, attn: Attention, hidden_states: torch.Tensor, encoder_hidden_states: Optional[torch.Tensor]=None, attention_mask: Optional[torch.Tensor]=None, temb: Optional[torch.Tensor]=None, scale: float=1.0) -> torch.Tensor:
        """Executes the attention mechanism and stores cross-attention probabilities."""
        batch_size, sequence_length, _ = hidden_states.shape
        is_cross = encoder_hidden_states is not None
        context = encoder_hidden_states if is_cross else hidden_states
        
        heads = attn.heads
        dim_head = attn.to_q.out_features // heads

        query = attn.to_q(hidden_states)
        key = attn.to_k(context)
        value = attn.to_v(context)

        query = query.view(batch_size, -1, heads, dim_head).transpose(1, 2).reshape(batch_size * heads, -1, dim_head)
        key = key.view(batch_size, -1, heads, dim_head).transpose(1, 2).reshape(batch_size * heads, -1, dim_head)
        value = value.view(batch_size, -1, heads, dim_head).transpose(1, 2).reshape(batch_size * heads, -1, dim_head)

        attn_scores = torch.bmm(query, key.transpose(1, 2)) * scale
        attn_probs = attn_scores.softmax(dim=-1)

        if is_cross:
            self.attention_probs.append(attn_probs.detach().cpu())

        hidden_states = torch.bmm(attn_probs, value)
        hidden_states = hidden_states.reshape(batch_size, heads, -1, dim_head).transpose(1, 2).reshape(batch_size, -1, heads * dim_head)
        hidden_states = attn.to_out[0](hidden_states) 
        hidden_states = attn.to_out[1](hidden_states) 
        return hidden_states

class trace:
    """Context manager for tracing UNet cross-attention.
    
    Temporarily injects the `CaptureAttnProcessor` into all cross-attention 
    layers of the UNet. Once the generation block exits, it automatically 
    restores the original processors to prevent memory leaks.
    """
    def __init__(self, pipeline: Any):
        """Initializes the tracer.

        Args:
            pipeline (StableDiffusionPipeline): The loaded Hugging Face Diffusers pipeline.
        """
        self.pipeline = pipeline
        self.original_processors = {}
        self.capture_processor = CaptureAttnProcessor()

    def __enter__(self):
        """Injects custom attention hooks into the UNet."""
        unet = self.pipeline.unet
        for name, module in unet.named_modules():
            if name.endswith("attn2") and hasattr(module, "set_processor"):
                self.original_processors[name] = module.processor
                module.set_processor(self.capture_processor)
        return self

    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any):
        """Restores the original attention processors."""
        unet = self.pipeline.unet
        for name, module in unet.named_modules():
            if name in self.original_processors:
                module.set_processor(self.original_processors[name])

    def compute_heat_maps(self) -> Dict[int, CustomDAAMHeatmap]:
        """Aggregates and upscales the captured attention maps.
        
        Averages the attention across all heads and specific UNet layers (typically 16x16 
        up to 64x64 latent spaces), then uses bicubic interpolation to upscale the 
        resulting matrices to a unified 64x64 grid for interactive visualization.

        Returns:
            Dict[int, CustomDAAMHeatmap]: A dictionary mapping the token index (int) to its corresponding upscaled heatmap object.

        Raises:
            ValueError: If no attention maps were captured during the tracing process.
        """
        if not self.capture_processor.attention_probs:
            raise ValueError("No attention captured.")

        all_maps = self.capture_processor.attention_probs

        valid_maps = []
        for m in all_maps:
            num_pixels = m.shape[1]
            if 256 <= num_pixels <= 4096:
                valid_maps.append(m)

        if not valid_maps:
            print("No valid attention maps found. Using all captured maps.")
            valid_maps = all_maps

        num_tokens = valid_maps[0].shape[-1]
        
        target_dim = 64 
        accumulated_maps = torch.zeros(target_dim, target_dim, num_tokens)
        count = 0

        for m in valid_maps:
            m_avg_heads = m.mean(dim=0) 
            
            side = int(np.sqrt(m_avg_heads.shape[0]))
            if side * side != m_avg_heads.shape[0]: continue
            
            m_2d = m_avg_heads.view(side, side, num_tokens)
            m_permuted = m_2d.permute(2, 0, 1).unsqueeze(1) 
            
            m_resized = torch.nn.functional.interpolate(
                m_permuted.to(torch.float32), 
                size=(target_dim, target_dim), 
                mode='bicubic', 
                align_corners=False
            ).to(m_permuted.dtype)
            
            accumulated_maps += m_resized.squeeze(1).permute(1, 2, 0)
            count += 1

        if count > 0:
            accumulated_maps /= count

        results = {}
        for token_idx in range(num_tokens):
            token_map = accumulated_maps[:, :, token_idx]
            if token_map.max() > 0:
                results[token_idx] = CustomDAAMHeatmap(token_map)
                
        return results